FROM ubuntu:22.04

# install 
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install cmake -y
RUN apt-get install python3-pip -y
RUN apt-get install git -y
RUN apt-get install wget -y
RUN apt-get install zip -y
RUN apt-get install build-essential -y
RUN apt-get install xxd -y
RUN apt-get install sqlite3 -y
RUN apt-get install uuid-dev -y
RUN pip install conan

WORKDIR /tmp
RUN wget https://github.com/rui314/mold/releases/download/v1.10.1/mold-1.10.1-$(arch)-linux.tar.gz
RUN tar -zxvf /tmp/mold-1.10.1-$(arch)-linux.tar.gz
RUN cp /tmp/mold-1.10.1-$(arch)-linux/bin/mold /usr/local/bin/mold
RUN ln -s /usr/local/bin/mold /usr/local/bin/ld.mold

WORKDIR /root
COPY . .
WORKDIR /root/lib
RUN git clone  https://gitlab.com/jobol/mustach.git
WORKDIR /root/lib/mustach
RUN git checkout 1.2.5

WORKDIR /root
RUN make hard_build

CMD ./build/c_server_test
